#
# TODO: Use the new bats-core repo.
#

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6

    working_directory: ~/repo

    steps:
      - run: sudo apt-get install jq
      - run: sudo git clone https://github.com/sstephenson/bats.git
      - run: pushd bats && sudo bash install.sh /usr/local && popd && sudo rm -rf bats

      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

workflows:
  version: 2
  test_and_publish:
    jobs:
      - build
